/*
    Name: prox_sens.c
    Description: This file provides functions to initialize and read Ultrasonic Sensor
    Date: 2019-10-21
    Author(s): Martin Lauersen
*/

#include "prox_sens.h"
#include "main.h"

int prox_Flag = 0;
extern float RPYA[4];

/*  Function: prox_init
    Purpose: Optional initialisation function for the timer (copy of the autogenerated one from CubeMX)
    Parameters: N/A
    Returns: N/A
*/
/*
void prox_Init(void)
{
    TIM_MasterConfigTypeDef sMasterConfig = {0};
    TIM_OC_InitTypeDef sConfigOC = {0};
    htim2.Instance = TIM2;
    htim2.Init.Prescaler = 14;
    htim2.Init.CounterMode = TIM_COUNTERMODE_UP;
    htim2.Init.Period = 65000;
    htim2.Init.ClockDivision = TIM_CLOCKDIVISION_DIV1;
    htim2.Init.AutoReloadPreload = TIM_AUTORELOAD_PRELOAD_ENABLE;
    if (HAL_TIM_OC_Init(&htim2) != HAL_OK)
    {
        Error_Handler();
    }
    sMasterConfig.MasterOutputTrigger = TIM_TRGO_RESET;
    sMasterConfig.MasterSlaveMode = TIM_MASTERSLAVEMODE_DISABLE;
    if (HAL_TIMEx_MasterConfigSynchronization(&htim2, &sMasterConfig) != HAL_OK)
    {
        Error_Handler();
    }
    sConfigOC.OCMode = TIM_OCMODE_TIMING;
    sConfigOC.Pulse = 0;
    sConfigOC.OCPolarity = TIM_OCPOLARITY_HIGH;
    sConfigOC.OCFastMode = TIM_OCFAST_DISABLE;
    if (HAL_TIM_OC_ConfigChannel(&htim2, &sConfigOC, TIM_CHANNEL_1) != HAL_OK)
    {
        Error_Handler();
    }
}
*/
/*
    Function: prox_Start
    Description: Sends the initial pulse to the proximity sensor
    Parameters: N/A
    Returns: N/A
 */
void prox_Start(void)
{
    // Send short 1ms pulse to proximity sensor
    HAL_GPIO_WritePin(GPIOA , GPIO_PIN_11, GPIO_PIN_SET);
    HAL_Delay(1);
    HAL_GPIO_WritePin(GPIOA , GPIO_PIN_11, GPIO_PIN_RESET);
    // Set prox status flag to 1
    prox_Flag = 1;
}
/*
    Function: prox_Interrupt
    Description: This function is called in the interrupt
    Parameters: N/A
    Returns: N/A
 */
void prox_Interrupt(void)
{
        // If the flag is 1, reset counter and increment flag value
		if(prox_Flag == 1){
			TIM2->CNT = 0x0000; // Set counter to 0
			prox_Flag = 2;    // Increment flag val
		}
        // If the flag is 2, read counter value and increment flag
		else if (prox_Flag == 2){
			// Store value of counter
            int counter_Val = TIM2->CNT;
			// Increment flag
            prox_Flag = 3;
            // Get distance
			RPYA[3] = prox_DistCalc((float)counter_Val);
			//while(1);// debug
    }
}

/*
    Function: prox_DistCalc
    Description: Calculates measured distance, using size of counter
    Parameters: float -> counter_Val -> Value of the counter of timer
    Returns: float -> Measured distance in meters(?)
 */
float prox_DistCalc(float counter_Val)
{
    // Multiply counter by ((prescaler/clk)*(340/2 ms)) -> (15/72e6)*(340/2)=0.000035416666
    return(0.000035416666 * counter_Val);
}
